# XXX: enable istio-inject on default NS
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
# XXX: Ensure istio-system ns present to create the cacerts secrets in
# (takes a while until the operator creates all resources defined in IstioControlPlane)
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: v1
data:
  ca-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVFekNDQXZ1Z0F3SUJBZ0lVRHp4dERlb3RqTHVuWW80Wmx5NUJyNWh6SFBzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdUQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIRXdoTwpaWGNnV1c5eWF6RVFNQTRHQTFVRUNoTUhRV3hsZEdocGJ6RU9NQXdHQTFVRUN4TUZVM1JoWTJzeEhUQWJCZ05WCkJBTVRGR2x6ZEdsdkxuTjBZV05yTG1Gc1pYUm9MbWx2TUI0WERURTVNVEl5TWpFM05ERXdNRm9YRFRJME1USXkKTURFM05ERXdNRm93Z1l3eEN6QUpCZ05WQkFZVEFsVlRNUkV3RHdZRFZRUUlFd2hPWlhjZ1dXOXlhekVSTUE4RwpBMVVFQnhNSVRtVjNJRmx2Y21zeEVEQU9CZ05WQkFvVEIwRnNaWFJvYVc4eEdqQVlCZ05WQkFzVEVWTjBZV05yCkwyMXBibWxyZFdKbExXTXhNU2t3SndZRFZRUURFeUJ0YVc1cGEzVmlaUzFqTVM1cGMzUnBieTV6ZEdGamF5NWgKYkdWMGFDNXBiekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQYVllQnFjdXBmUwowK0dUS0tRY0NVOGxuSHlRaTlCYnFqUjZMZHNvMEhLMGg3Y0RCckhDZndCSCtZRE9wY2l2S0h0NmVrZlh5bW9wClZoNDNLRmY2S2hFOHBPMHNNTE9wRC9iUjVnK1B4c1RQMnFDVVNHUjViUThJZDErKzFuRktEQ0tvQS8wVTFvOHAKMXUxNEtjd1puQ0M5NXRDczRnZnJzSCtCaEZna0tJQmg0Q1hXSEFVUi9qNytFSW0zdm1wWFgxY2Zua3I1L09jOQpiaU5rVFJFQjVxL3A2SEN0MmpPTXpDNjVBQnhGU2dXdnozWGtvY09Qd216RUVYeDEralZ1WDZ6YUlNN3IyQnFRCmFLRmtMZ2d3cDJodDM1dlUrZ3VqWEN3cnRCN1VXZmc3bTFCS3R3MlVicUNxL2dkZnpDbTVhajRCS2IvOGpqYmkKamQrbVg1RjF3Y2tDQXdFQUFhT0JnekNCZ0RBT0JnTlZIUThCQWY4RUJBTUNBYVl3SFFZRFZSMGxCQll3RkFZSQpLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGS25aCnRSVVYwMnhKM1pRZnN3WFZ2U0E0WDU2Y01COEdBMVVkSXdRWU1CYUFGRUNsaUdpR0owcEg3eVRKZzdkeTVXTFAKOWxyb01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ29JdXdrNkJNS29sSkl6WGNieU53cFZFM29WSFFkMmRvVgppWFRnKzRqRWYzMktEbURmVGJ5TEZLVk1GMmtlRFZ2TjhYS2xtNkUzY2Nycm5OTkltVXJINFFDOE53Z2JtQmlWCm1od0Z1allXblBhTHVpeEY3OHRTcEdRTXBlYVVCSnJBYklFUkc4Vk04K0cvcWlzU0tweWRWZWNIVGFGc0lxQnUKRlpuZkIvZGsrQnZhNkVFZHlNY2tTbUZUd0Z3UlRVSUEzLzE4NzhkWW5INmE1VzE1M291ZDlENHprVStBdmNoQgpyL2syOVVNVzlGUHNoeWVFME84Y1dFRWNzSEJyYTg1Q0doNnVKRHZ5UHhHbzhCNzN4aUNHVnpqdXJHNmJVcEt4ClRSa0pTa0Y2RnJyVmE5MDdQUHY3MklLVktrRWZBUHZYY3FnK0JRYjc3NjVqdkJXbTM1cGcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  ca-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBOXBoNEdweTZsOUxUNFpNb3BCd0pUeVdjZkpDTDBGdXFOSG90MnlqUWNyU0h0d01HCnNjSi9BRWY1Z002bHlLOG9lM3A2UjlmS2FpbFdIamNvVi9vcUVUeWs3U3d3czZrUDl0SG1ENC9HeE0vYW9KUkkKWkhsdER3aDNYNzdXY1VvTUlxZ0QvUlRXanluVzdYZ3B6Qm1jSUwzbTBLemlCK3V3ZjRHRVdDUW9nR0hnSmRZYwpCUkgrUHY0UWliZSthbGRmVngrZVN2bjg1ejF1STJSTkVRSG1yK25vY0szYU00ek1McmtBSEVWS0JhL1BkZVNoCnc0L0NiTVFSZkhYNk5XNWZyTm9nenV2WUdwQm9vV1F1Q0RDbmFHM2ZtOVQ2QzZOY0xDdTBIdFJaK0R1YlVFcTMKRFpSdW9LcitCMS9NS2JscVBnRXB2L3lPTnVLTjM2WmZrWFhCeVFJREFRQUJBb0lCQURvcjFZbFJsNkxoRlNLTgplSFRlT0VQM2QyYmJJbUJRZjJKSndDK0cvVVZSMlFJUE1MRVdWS2RZVXo5VGdFQkxNWjJQVXZGSHNuUkF0QlFFCnB2dTZBOXAxRitMckhjSUVDOFFKMTkrcjV4UGVoSkNFNmw3cFZoVEp4bjlMb1lLd0dSVEQxYzBKOFdOc1YwdEYKb1hhSVJCQmxPK0hXSnF2L3FXOHF1bkdnZGYxeW9zTThqbGFoWkxkVUY1K1NkS3lCT0hCdnVKN0hxTmZpcmEwOAo0dG9obVpWODlNQ2NUancvcTM0K3d6blhPY0VWcS9VaFdiWTNXeklvek5pUkxYUDgwbGU2eGhkemlYYmkvdEd2CjBvNW0zK2h3V0UzcTdVeFJsc0ZVbVVnYW5FbmZET3lLb3ErU2puR3dSb3l3UTc0VDRrM250QTlFdHhTT21neEgKR2RhU2ZnRUNnWUVBLzBQREt4SnNhTGdQMVZpVE82Q1Q3OUxhdWduZ21Gd2dyL2UrK0d4elpvYkZKbFkyRFF5OApVdjVpV2hyTU5aTmNFWmVEdmxRVWg2WHJBRWJoS2RmcDV6eTdpWnJ0MG1GcHpiTWJJUGpFdG5GMDV2cEhQUlB3CldybCtOUnVOcmdFRzdOZTlUYkgyWTNZdlF1R3JFVUVZTjltRk5HWExFZm11WjU5NzFublB2VGtDZ1lFQTkwNVEKWWJHc25hbDkrc0FjU3lybVFvUHZiaTVxaVpPWkxHTTl2S1lTbEMzTjR1NGprYW02ODM1MWZXUzRKSWxpOVdUUQpsSjlhRnFkQThOMGZuQ2NJeFRJYXlQbXRtT3lzb3pMdGduVjNmb1Z3MkZaQnRuMHVuY2dRMzA2NFUwUzJVd0dxCnhFTTQzbU1BM0QvQmtwbEpLZUovUE5aZk54RjE0TW5Jelo1TXVSRUNnWUF3OXJPS0lJZVE4clYreS9XNSsweEYKTldIbFM1MjhPL2U5S1QyRmMzQVRXNGlYbVBQWFB2a2t4a3poVWNDWUNrTWYwTHRobDhrMFY5d2krbldZVENVKwp5TVNFV2FhQ3MxTFROU2JnQlRmZWN4YmtjMStVMUsxSENjdXVyakZZRGpSZzIrVWc4U0Q4NVIrZHFhSGh0bVhKCjJMeVhWMnREY0d4R3ppMjM3emVzNlFLQmdBUXFmWkFudmhDcDJrVnZGd3J0SGhQZ3hSZkdFR1ZnNXlPb1NGSDEKT2pya3lxTVgvK0ZrU3BIdmYyc3RWeXpHWTdSZWptVHlpa0gzYjFDZmFQam9iMjFpK3JDSUJEU2ZTQWszd21pQQpNaE1makZjWW5PTEdHUkx2VzlsbktoTzlCSlZCWWU4TWN0ak1NaWVEcTI4Y3hlNitzZ1lFVm5aSEJRVlVZTjJWCjNSVUJBb0dCQUpCMFBYUDRROEc3dGhBQnQ4N092VEpoN2w3bmR0UFdoRTRHQm55ZUJCekFaSlhkbjk3Q0ljTnEKbVF4MzJUV28zNjR2WEswWXpxTmRBMFJVMi9MZ3JocHZsUktQblZLazViR0pzb1prcHZrVUo5aUVBZ0ZGdWo3bgp0QjZOREVFaUhrR3J1ZmJnTnNEeDNoekFxSkRMSElxbEw3dEM1SFN0SThYR2JoTW5wMEZ2Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  cert-chain.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVWldBcWdEejdva2YwQjhjcG5KSzlLNUdFbWN3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdUQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIRXdoTwpaWGNnV1c5eWF6RVFNQTRHQTFVRUNoTUhRV3hsZEdocGJ6RU9NQXdHQTFVRUN4TUZVM1JoWTJzeEhUQWJCZ05WCkJBTVRGR2x6ZEdsdkxuTjBZV05yTG1Gc1pYUm9MbWx2TUI0WERURTVNVEV5TnpBNE1UWXdNRm9YRFRJME1URXkKTlRBNE1UWXdNRm93ZERFTE1Ba0dBMVVFQmhNQ1ZWTXhFVEFQQmdOVkJBZ1RDRTVsZHlCWmIzSnJNUkV3RHdZRApWUVFIRXdoT1pYY2dXVzl5YXpFUU1BNEdBMVVFQ2hNSFFXeGxkR2hwYnpFT01Bd0dBMVVFQ3hNRlUzUmhZMnN4CkhUQWJCZ05WQkFNVEZHbHpkR2x2TG5OMFlXTnJMbUZzWlhSb0xtbHZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2R2dBeHBHdXZFbnJRMS9LYjFyK3FqRGtobVBCeEI1RVhDMmRtSEt5ZlhXNgo2WmhlOW16Z0l3cjZ1RE5mZU9DWi8rWGxEYkoxR3RIUFNpUERVeWNkUGIyVUJ4eXpYQjFnMktzQmVvUGRPR25aCjF0VEhTbUZCZGY3VkR6clFxSVd2aUt0S0dIMmJHb2ZSR2JWRzBjU3pUSDVpdWFrNEc0TkZMbU5DaGpDTmlFMTIKRi9mZHljOFdORTlEVElzSE9rOElWeGlnOExDK2ZiUUYyTW8zLzNxMHA1UW5FaGNKWlBQNGNlejRNbEs1bENJTwp0MFFQSmRULzY1S2ZkMDFNYmtqM0dMNUYrRzhVeXZEemxoY08zc2ZlUFVGVHd5ZUFqVmlmMkt2VWxEOFpPSWxrClQ1QTlkem95TTlYNmdSeEZqQTBobG5tU1lnK0dka2hycXFPYjJpQWNIUUlEQVFBQm8wSXdRREFPQmdOVkhROEIKQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUUtXSWFJWW5Ta2Z2Sk1tRAp0M0xsWXMvMld1Z3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRS9EZWpPU0lwc1ZVMkZua00wem5PQURhUlRaCm9NY2l0VFJ6ZHp4YTNWQlNvdGZxRCtCUGsyYVEzVUFYelJCRDFiZXhxMEJjMzdaQnRTcldzN0lvVTFpUVorc1oKU1p5WWE4TDBrUkFMb0pzNjVpK2xCNklmWVFycDFqSGJNOW1iMXpxRitlKzVYUDdMY3Y0MWxvR05JSytZWkhkZgpJVjNiMnVxWnpUTDBER0JPQzlWN0JranpNMVg4WGNHZGRLMW1MQTdMYUphRjBWQ0UzaitVYkY0czNDMHpiblJvCkFHY2JvUGNZRVFySFZvUytCOE1QMGppMUsxMXNPekFxRWVUYWRlVC96cFlCQWRrWGpVS1VnVXZXM2dHMXBSb0EKOHNhQk1RdjJtdnk2MjROZGRrSys3ZWUvQWhNenhra1NSWGtCN1NHYmJMMGlDSUlDRERzZzlrazMrZWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVFekNDQXZ1Z0F3SUJBZ0lVRHp4dERlb3RqTHVuWW80Wmx5NUJyNWh6SFBzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdUQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIRXdoTwpaWGNnV1c5eWF6RVFNQTRHQTFVRUNoTUhRV3hsZEdocGJ6RU9NQXdHQTFVRUN4TUZVM1JoWTJzeEhUQWJCZ05WCkJBTVRGR2x6ZEdsdkxuTjBZV05yTG1Gc1pYUm9MbWx2TUI0WERURTVNVEl5TWpFM05ERXdNRm9YRFRJME1USXkKTURFM05ERXdNRm93Z1l3eEN6QUpCZ05WQkFZVEFsVlRNUkV3RHdZRFZRUUlFd2hPWlhjZ1dXOXlhekVSTUE4RwpBMVVFQnhNSVRtVjNJRmx2Y21zeEVEQU9CZ05WQkFvVEIwRnNaWFJvYVc4eEdqQVlCZ05WQkFzVEVWTjBZV05yCkwyMXBibWxyZFdKbExXTXhNU2t3SndZRFZRUURFeUJ0YVc1cGEzVmlaUzFqTVM1cGMzUnBieTV6ZEdGamF5NWgKYkdWMGFDNXBiekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQYVllQnFjdXBmUwowK0dUS0tRY0NVOGxuSHlRaTlCYnFqUjZMZHNvMEhLMGg3Y0RCckhDZndCSCtZRE9wY2l2S0h0NmVrZlh5bW9wClZoNDNLRmY2S2hFOHBPMHNNTE9wRC9iUjVnK1B4c1RQMnFDVVNHUjViUThJZDErKzFuRktEQ0tvQS8wVTFvOHAKMXUxNEtjd1puQ0M5NXRDczRnZnJzSCtCaEZna0tJQmg0Q1hXSEFVUi9qNytFSW0zdm1wWFgxY2Zua3I1L09jOQpiaU5rVFJFQjVxL3A2SEN0MmpPTXpDNjVBQnhGU2dXdnozWGtvY09Qd216RUVYeDEralZ1WDZ6YUlNN3IyQnFRCmFLRmtMZ2d3cDJodDM1dlUrZ3VqWEN3cnRCN1VXZmc3bTFCS3R3MlVicUNxL2dkZnpDbTVhajRCS2IvOGpqYmkKamQrbVg1RjF3Y2tDQXdFQUFhT0JnekNCZ0RBT0JnTlZIUThCQWY4RUJBTUNBYVl3SFFZRFZSMGxCQll3RkFZSQpLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGS25aCnRSVVYwMnhKM1pRZnN3WFZ2U0E0WDU2Y01COEdBMVVkSXdRWU1CYUFGRUNsaUdpR0owcEg3eVRKZzdkeTVXTFAKOWxyb01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ29JdXdrNkJNS29sSkl6WGNieU53cFZFM29WSFFkMmRvVgppWFRnKzRqRWYzMktEbURmVGJ5TEZLVk1GMmtlRFZ2TjhYS2xtNkUzY2Nycm5OTkltVXJINFFDOE53Z2JtQmlWCm1od0Z1allXblBhTHVpeEY3OHRTcEdRTXBlYVVCSnJBYklFUkc4Vk04K0cvcWlzU0tweWRWZWNIVGFGc0lxQnUKRlpuZkIvZGsrQnZhNkVFZHlNY2tTbUZUd0Z3UlRVSUEzLzE4NzhkWW5INmE1VzE1M291ZDlENHprVStBdmNoQgpyL2syOVVNVzlGUHNoeWVFME84Y1dFRWNzSEJyYTg1Q0doNnVKRHZ5UHhHbzhCNzN4aUNHVnpqdXJHNmJVcEt4ClRSa0pTa0Y2RnJyVmE5MDdQUHY3MklLVktrRWZBUHZYY3FnK0JRYjc3NjVqdkJXbTM1cGcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  root-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVWldBcWdEejdva2YwQjhjcG5KSzlLNUdFbWN3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdUQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIRXdoTwpaWGNnV1c5eWF6RVFNQTRHQTFVRUNoTUhRV3hsZEdocGJ6RU9NQXdHQTFVRUN4TUZVM1JoWTJzeEhUQWJCZ05WCkJBTVRGR2x6ZEdsdkxuTjBZV05yTG1Gc1pYUm9MbWx2TUI0WERURTVNVEV5TnpBNE1UWXdNRm9YRFRJME1URXkKTlRBNE1UWXdNRm93ZERFTE1Ba0dBMVVFQmhNQ1ZWTXhFVEFQQmdOVkJBZ1RDRTVsZHlCWmIzSnJNUkV3RHdZRApWUVFIRXdoT1pYY2dXVzl5YXpFUU1BNEdBMVVFQ2hNSFFXeGxkR2hwYnpFT01Bd0dBMVVFQ3hNRlUzUmhZMnN4CkhUQWJCZ05WQkFNVEZHbHpkR2x2TG5OMFlXTnJMbUZzWlhSb0xtbHZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2R2dBeHBHdXZFbnJRMS9LYjFyK3FqRGtobVBCeEI1RVhDMmRtSEt5ZlhXNgo2WmhlOW16Z0l3cjZ1RE5mZU9DWi8rWGxEYkoxR3RIUFNpUERVeWNkUGIyVUJ4eXpYQjFnMktzQmVvUGRPR25aCjF0VEhTbUZCZGY3VkR6clFxSVd2aUt0S0dIMmJHb2ZSR2JWRzBjU3pUSDVpdWFrNEc0TkZMbU5DaGpDTmlFMTIKRi9mZHljOFdORTlEVElzSE9rOElWeGlnOExDK2ZiUUYyTW8zLzNxMHA1UW5FaGNKWlBQNGNlejRNbEs1bENJTwp0MFFQSmRULzY1S2ZkMDFNYmtqM0dMNUYrRzhVeXZEemxoY08zc2ZlUFVGVHd5ZUFqVmlmMkt2VWxEOFpPSWxrClQ1QTlkem95TTlYNmdSeEZqQTBobG5tU1lnK0dka2hycXFPYjJpQWNIUUlEQVFBQm8wSXdRREFPQmdOVkhROEIKQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUUtXSWFJWW5Ta2Z2Sk1tRAp0M0xsWXMvMld1Z3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRS9EZWpPU0lwc1ZVMkZua00wem5PQURhUlRaCm9NY2l0VFJ6ZHp4YTNWQlNvdGZxRCtCUGsyYVEzVUFYelJCRDFiZXhxMEJjMzdaQnRTcldzN0lvVTFpUVorc1oKU1p5WWE4TDBrUkFMb0pzNjVpK2xCNklmWVFycDFqSGJNOW1iMXpxRitlKzVYUDdMY3Y0MWxvR05JSytZWkhkZgpJVjNiMnVxWnpUTDBER0JPQzlWN0JranpNMVg4WGNHZGRLMW1MQTdMYUphRjBWQ0UzaitVYkY0czNDMHpiblJvCkFHY2JvUGNZRVFySFZvUytCOE1QMGppMUsxMXNPekFxRWVUYWRlVC96cFlCQWRrWGpVS1VnVXZXM2dHMXBSb0EKOHNhQk1RdjJtdnk2MjROZGRrSys3ZWUvQWhNenhra1NSWGtCN1NHYmJMMGlDSUlDRERzZzlrazMrZWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: cacerts
  namespace: istio-system
type: Opaque

---
# XXX: set resource requests to 0 to ensure scheduling on the small minikube default config'ed node
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: main
  namespace: istio-operator
spec:
  hub: istio
  tag: 1.4.3
  autoInjection:
    components:
      injector:
        enabled: true
    enabled: true
  cni:
    components:
      cni:
        enabled: false
    enabled: false
  configManagement:
    components:
      galley:
        enabled: true
        k8s:
          resources:
            requests:
              cpu: "0"
              memory: "0"
    enabled: true
  coreDNS:
    components:
      coreDNS:
        enabled: true
        k8s:
          resources: {}
    enabled: true
  gateways:
    components:
      egressGateway:
        enabled: false
        k8s:
          env:
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: external
          resources: {}
      ingressGateway:
        enabled: true
        k8s:
          resources: {}
    enabled: true
  policy:
    components:
      policy:
        enabled: false
    enabled: false
  security:
    components:
      certManager:
        enabled: false
      citadel:
        enabled: true
      nodeAgent:
        enabled: false
    enabled: true
  telemetry:
    components:
      telemetry:
        enabled: false
    enabled: false
  trafficManagement:
    components:
      pilot:
        enabled: true
        k8s:
          resources:
            requests:
              cpu: "0"
              memory: "0"
      proxy:
        enabled: true
        k8s:
          resources:
            requests:
              cpu: "0"
              memory: "0"
    enabled: true
  values:
    global:
      controlPlaneSecurityEnabled: true
      multiCluster:
        enabled: true
      podDNSSearchNamespaces:
      - global
      proxy:
        resources:
          requests:
            cpu: "0"
            memory: "0"
    security:
      selfSigned: false

...
