apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: default
spec:
  addresses:
  - 240.0.0.5
  endpoints:
  # XXX: indeed, these won't understand mTLS; but this is just for a quick demp
  # in my original production setup i'm using actual istio endpoints here
  - address: www.google.com
    labels:
      to: google
    ports:
      http: 80
  - address: www.slashdot.org
    labels:
      to: slash
    ports:
      http: 80
  hosts:
  - foo.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS


